### ISSUE TITLE
1.1.17 windows xaero.minimap problem

### ISSUE THREAD

**Issue by 0subzero** [Kron4ek/minecraft-vortex-launcher#34]
Привет. Версия 1.1.17 не запускает майн без указания полного пути. (--gameDir .)

java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "gameDir" is null
	at xaero.minimap.XaeroMinimap.tryLoadLater(XaeroMinimap.java:207)
	at net.minecraft.class_310.handler$zpp001$onTickStart(class_310.java:7556)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "gameDir" is null
	at xaero.minimap.XaeroMinimap.loadClient(XaeroMinimap.java:157)
	at xaero.minimap.XaeroMinimap.onInitializeClient(XaeroMinimap.java:64)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Render thread
Stacktrace:
	at xaero.minimap.XaeroMinimap.tryLoadLater(XaeroMinimap.java:207)
	at net.minecraft.class_310.handler$zpp001$onTickStart(class_310.java:7556)

Если сделать батник и прописать путь руками, как было раньше, то всё работает.
Пустой майнкрафт работает, и судя по логу, это ксаера не работает с точкой, но, сами понимаете, кто щас без карты играет?

Короче, всех благ автору проги. Надеюсь, он найдёт решение без костылей )

**Comment by Kron4ek** [comment]
Привет. 

Ок, буду иметь в виду, что некоторым модам нужен корректный путь в gameDir. Интересно, много ли таких модов.

**Comment by jedai86** [comment]
Привет, я сделал форк и там поправил этот краш, gamedir теперь будет работать всегда корректно, и еще сделал некоторые улучшения, можно скачать тут https://github.com/jedai86/minecraft-vortex-launcher

**Comment by Kron4ek** [comment]
Исправил в версии 1.1.18.
