### ISSUE TITLE
Fabric Minecraft 1.21.3 won't launch

### ISSUE THREAD

**Issue by ndiruhniu** [Kron4ek/minecraft-vortex-launcher#91]
Mint 22 (ubuntu 24.04)
Java 21 from https://bell-sw.com
log:
ndiruhniu@mint:~/Games/Minecraft$ ./VLauncher 
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM (build 21.0.5+11-LTS, mixed mode, sharing)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/home/ndiruhniu/Games/Minecraft/libraries/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar!/org/objectweb/asm/ClassReader.class, jar:file:/home/ndiruhniu/Games/Minecraft/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar!/org/objectweb/asm/ClassReader.class
	at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:83)
	at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:345)
	... 1 more

**Comment by Kron4ek** [comment]
You can work around this issue by removing `libraries/org/ow2/asm/asm/9.3` directory and disabling "Download missing libraries on game start" in the launcher settings.

**Comment by ndiruhniu** [comment]
I tried, but now the mods are broken. Something like this:
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch'!

**Comment by ndiruhniu** [comment]
I don't even know what the problem is. In the Launcher or in Fabric Loader

**Comment by ndiruhniu** [comment]
The problem is in the launcher. I tried PrismLauncher and everything works there and does not download the asm 9.3 library.

**Comment by Kron4ek** [comment]
Fixed in the latest release, thanks for the repost.

**Comment by ndiruhniu** [comment]
Thank you for fixing it.
